version: '3.4'

# WIP for ELK - logging
# validate consul and ELK running- 

name: library-support-compose

services:
    consul:
        container_name: consul
        image: consul
        environment:
        - agent=--dev
        ports:
        - 8500:8500

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
        ports:
        - 9200:9200
        volumes:
        - E:\\docker-mounts\\elasticsearch:/usr/share/elasticsearch/data
        environment:
        - discovery.type=single-node
        - xpack.security.enabled=false
        - xpack.security.enrollment.enabled=false
        networks:
        - elastic

    kibana:
        container_name: kibana  
        image: docker.elastic.co/kibana/kibana:8.6.2
        ports:
        - 5601:5601
        depends_on:
        - elasticsearch
        environment:
        - ELASTICSEARCH_URL=http://localhost:9200
        networks:
        - elastic

networks:
    elastic:
        driver: bridge