// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Books.DbContext;

#nullable disable

namespace Repository.Books.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Repository.Books.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BOOK_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AUTHOR");

                    b.Property<int>("AvailableCopies")
                        .HasColumnType("int")
                        .HasColumnName("AVAILABLE_COPIES");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BOOK_NAME");

                    b.Property<int>("TotalCopies")
                        .HasColumnType("int")
                        .HasColumnName("TOTAL_COPIES");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dan Brown",
                            AvailableCopies = 5,
                            Name = "Da Vinci Code",
                            TotalCopies = 5
                        },
                        new
                        {
                            Id = 2,
                            Author = "Dan Brown",
                            AvailableCopies = 3,
                            Name = "The Deception Point",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 3,
                            Author = "Agatha Christi",
                            AvailableCopies = 3,
                            Name = "And then there were none",
                            TotalCopies = 3
                        },
                        new
                        {
                            Id = 4,
                            Author = "Abdul Kalam",
                            AvailableCopies = 5,
                            Name = "Wings of Fire",
                            TotalCopies = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
